// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fntpyyweuuddkkxfrhwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudHB5eXdldXVkZGtreGZyaHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTEzODUsImV4cCI6MjA3MTA4NzM4NX0.8BeIOyLuxEIHIQylO4DSvtl4S8TD4ybtPvpeHIzi4Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});